import type { TemplateDef, TemplateDesign } from "./types";

export const baseDesign: TemplateDesign = {
  accent: "#1e3a5f",
  headingFont: "sans",
  spacing: "normal",
  sectionStyle: "line",
  layout: "single",
  header: "stack",
  bullet: "disc",
  supportsPhoto: false,
};

export const defaultTemplates: TemplateDef[] = [
  {
    id: "classic-ats",
    name: { ar: "كلاسيكي ATS", en: "Classic ATS" },
    description: {
      ar: "عمود واحد هادئ بعناوين واضحة وفواصل دقيقة؛ مناسب للرفع المباشر إلى أنظمة التوظيف.",
      en: "A calm single-column layout with crisp headings and separators for ATS-first applications.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 1,
    design: {
      ...baseDesign,
      accent: "#203a5f",
      sectionStyle: "line",
      layout: "single",
      header: "stack",
      bullet: "disc",
    },
  },
  {
    id: "modern",
    name: { ar: "عصري", en: "Modern" },
    description: {
      ar: "ترويسة ممتدة ولمسات زمردية مع تسلسل بصري واضح بدون التضحية بالقراءة.",
      en: "Wide header, restrained emerald accents and strong hierarchy without sacrificing readability.",
    },
    category: "modern",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 2,
    design: {
      ...baseDesign,
      accent: "#0f766e",
      sectionStyle: "bar",
      layout: "single",
      header: "banner",
      bullet: "dash",
    },
  },
  {
    id: "executive",
    name: { ar: "تنفيذي", en: "Executive" },
    description: {
      ar: "طابع قيادي رصين، ترويسة موزعة ومساحات مريحة لملفات المديرين والخبرات العليا.",
      en: "A restrained leadership layout with split header and generous spacing for senior profiles.",
    },
    category: "executive",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 3,
    design: {
      ...baseDesign,
      accent: "#172033",
      headingFont: "serif",
      spacing: "airy",
      sectionStyle: "caps",
      layout: "single",
      header: "split",
      bullet: "square",
    },
  },
  {
    id: "minimal",
    name: { ar: "مبسّط", en: "Minimal" },
    description: {
      ar: "مساحات بيضاء مدروسة، ترويسة موسطة، ونبرة بصرية محايدة تناسب أغلب التخصصات.",
      en: "Measured whitespace, centered header and neutral visual tone for broad professional use.",
    },
    category: "minimal",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 4,
    design: {
      ...baseDesign,
      accent: "#334155",
      spacing: "airy",
      sectionStyle: "plain",
      layout: "single",
      header: "centered",
      bullet: "dash",
    },
  },
  {
    id: "saudi-professional",
    name: { ar: "سعودي مهني", en: "Saudi Professional" },
    description: {
      ar: "قالب عربي أولاً بترويسة خضراء وعمود جانبي منظم للمهارات واللغات والروابط؛ بصري أكثر من قوالب ATS أحادية العمود.",
      en: "Arabic-first profile with green banner and organized sidebar; more visual than Seerati's single-column ATS templates.",
    },
    category: "modern",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 5,
    design: {
      ...baseDesign,
      accent: "#166534",
      sectionStyle: "bar",
      layout: "sidebar",
      header: "banner",
      bullet: "disc",
      supportsPhoto: true,
    },
  },
  {
    id: "creative",
    name: { ar: "إبداعي", en: "Creative" },
    description: {
      ar: "شخصية بصرية أقوى مع عمود جانبي وصورة اختيارية؛ مناسب للأعمال الإبداعية أكثر من أنظمة ATS الصارمة.",
      en: "A stronger visual identity with sidebar and optional photo, aimed at creative roles rather than strict ATS flows.",
    },
    category: "creative",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 6,
    design: {
      ...baseDesign,
      accent: "#5b2a86",
      spacing: "compact",
      sectionStyle: "plain",
      layout: "sidebar-left",
      header: "stack",
      bullet: "square",
      supportsPhoto: true,
    },
  },
  {
    id: "riyadh-modern",
    name: { ar: "رياض مودرن", en: "Riyadh Modern" },
    description: {
      ar: "هوية حضرية هادئة بالأزرق النيلي، مناسبة للتقنية والاستشارات والمنتجات الرقمية.",
      en: "A quiet urban indigo identity for technology, consulting and digital product roles.",
    },
    category: "modern",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 7,
    design: {
      ...baseDesign,
      accent: "#24456f",
      sectionStyle: "bar",
      layout: "single",
      header: "split",
      bullet: "dash",
    },
  },
  {
    id: "saudi-executive",
    name: { ar: "سعودي تنفيذي", en: "Saudi Executive" },
    description: {
      ar: "قالب قيادي بلمسة خضراء داكنة وتوزيع متزن للمعلومات يناسب المدراء والتنفيذيين.",
      en: "A leadership-focused Saudi profile with deep green accents and balanced information density.",
    },
    category: "executive",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 8,
    design: {
      ...baseDesign,
      accent: "#14532d",
      headingFont: "serif",
      spacing: "airy",
      sectionStyle: "line",
      layout: "single",
      header: "split",
      bullet: "square",
    },
  },
  {
    id: "gulf-professional",
    name: { ar: "خليجي مهني", en: "Gulf Professional" },
    description: {
      ar: "تنسيق مهني نظيف مناسب للسوق الخليجي، مع عمود جانبي خفيف وقراءة بشرية ممتازة.",
      en: "A polished GCC-oriented profile with a light sidebar optimized for human scanning rather than strict ATS parsing.",
    },
    category: "modern",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 9,
    design: {
      ...baseDesign,
      accent: "#0f5f5a",
      sectionStyle: "line",
      layout: "sidebar",
      header: "stack",
      bullet: "disc",
      supportsPhoto: true,
    },
  },
  {
    id: "finance",
    name: { ar: "مالية واستثمار", en: "Finance & Investment" },
    description: {
      ar: "قالب رسمي عالي الانضباط للمالية والمحاسبة والاستثمار، يبرز الخبرة والأرقام بدون زخرفة زائدة.",
      en: "A disciplined formal layout for finance, accounting and investment, emphasizing evidence and measurable impact.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 10,
    design: {
      ...baseDesign,
      accent: "#25344f",
      headingFont: "serif",
      spacing: "normal",
      sectionStyle: "caps",
      layout: "single",
      header: "split",
      bullet: "square",
    },
  },
  {
    id: "technology",
    name: { ar: "تقنية ومنتجات", en: "Technology & Product" },
    description: {
      ar: "قالب مدمج وسريع المسح البصري للبرمجة والبيانات والمنتجات مع إبراز المهارات والمشاريع.",
      en: "A compact, scan-friendly layout for engineering, data and product profiles with clear skills and projects.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 11,
    design: {
      ...baseDesign,
      accent: "#075985",
      spacing: "compact",
      sectionStyle: "bar",
      layout: "single",
      header: "stack",
      bullet: "dash",
    },
  },
  {
    id: "graduate",
    name: { ar: "خريج وبداية مهنية", en: "Graduate & Early Career" },
    description: {
      ar: "تنسيق واضح للخريجين وبدايات المسار، يعطي مساحة أكبر للتعليم والمشاريع والتطوع والمهارات.",
      en: "A clear early-career layout that gives more visual room to education, projects, volunteering and skills.",
    },
    category: "minimal",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 12,
    design: {
      ...baseDesign,
      accent: "#365314",
      spacing: "normal",
      sectionStyle: "plain",
      layout: "single",
      header: "centered",
      bullet: "disc",
    },
  },
  {
    id: "royal-executive",
    name: { ar: "تنفيذي سعودي فاخر", en: "Saudi Luxe Executive" },
    description: {
      ar: "رأس أنيق بخط مطبعي رصين وتباعد واسع؛ مصمم للمناصب القيادية والملفات التنفيذية.",
      en: "An elegant serif header with generous spacing, built for leadership and executive profiles.",
    },
    category: "executive",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 13,
    design: {
      ...baseDesign,
      accent: "#0b3b2e",
      headingFont: "serif",
      spacing: "airy",
      sectionStyle: "caps",
      layout: "single",
      header: "banner",
      bullet: "square",
    },
  },
  {
    id: "ats-strict",
    name: { ar: "ATS صارم بسيط", en: "Strict ATS" },
    description: {
      ar: "عمود واحد بدون أي رسومات أو أعمدة، أعلى توافق ممكن مع أنظمة تتبع المتقدمين.",
      en: "One column, zero graphics or sidebars — the highest possible applicant-tracking compatibility.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 14,
    design: {
      ...baseDesign,
      accent: "#111827",
      headingFont: "sans",
      spacing: "normal",
      sectionStyle: "plain",
      layout: "single",
      header: "stack",
      bullet: "disc",
    },
  },
  {
    id: "modern-two-column",
    name: { ar: "حديث بعمودين", en: "Modern Two Column" },
    description: {
      ar: "عمود جانبي للمهارات واللغات والتواصل مع عمود رئيسي للخبرات؛ أنيق وسهل المسح البصري.",
      en: "A sidebar for skills, languages and contact next to a main experience column — elegant and easy to scan.",
    },
    category: "modern",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 15,
    design: {
      ...baseDesign,
      accent: "#1d4ed8",
      spacing: "normal",
      sectionStyle: "bar",
      layout: "sidebar",
      header: "split",
      bullet: "dash",
      supportsPhoto: true,
    },
  },
  {
    id: "creative-tech",
    name: { ar: "إبداعي تقني", en: "Creative Tech" },
    description: {
      ar: "لمسات لونية جسورة ومساحة بارزة للمشاريع والأدوات؛ مناسب للمصممين والمطورين.",
      en: "Bold accent colour with prominent room for projects and tooling — made for designers and developers.",
    },
    category: "creative",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 16,
    design: {
      ...baseDesign,
      accent: "#7c3aed",
      spacing: "compact",
      sectionStyle: "bar",
      layout: "sidebar-left",
      header: "centered",
      bullet: "square",
      supportsPhoto: true,
    },
  },
  {
    id: "cloud-flow",
    name: { ar: "كلاود فلو", en: "Cloud Flow" },
    description: {
      ar: "تصميم أبيض نقي بلمسة أزرق كهربائي وعناوين رفيعة ومسافات مدروسة — أسلوب تطبيق حديث مع توافق ATS كامل.",
      en: "Crisp white sheet, electric blue accents and airy thin headings — a modern app-grade look that stays fully ATS-safe.",
    },
    category: "modern",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 17,
    design: {
      ...baseDesign,
      accent: "#3b82f6",
      spacing: "airy",
      sectionStyle: "line",
      layout: "single",
      header: "split",
      bullet: "dash",
    },
  },
  {
    id: "cloud-flow-duo",
    name: { ar: "كلاود فلو مزدوج", en: "Cloud Flow Duo" },
    description: {
      ar: "عمودان متوازنان: الخبرات في المتن، والمهارات واللغات والروابط في عمود أزرق فاتح سهل المسح.",
      en: "Two balanced columns: experience in the main flow, skills, languages and links in a light blue scan column.",
    },
    category: "modern",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 18,
    design: {
      ...baseDesign,
      accent: "#2563eb",
      spacing: "normal",
      sectionStyle: "bar",
      layout: "sidebar",
      header: "banner",
      bullet: "disc",
      supportsPhoto: true,
    },
  },
  {
    id: "cloud-compact",
    name: { ar: "كلاود مكثّف", en: "Cloud Compact" },
    description: {
      ar: "كثافة عالية بذكاء: صفحة واحدة تكفي لخبرة طويلة دون فقدان الوضوح، مثالية للتقنية والاستشارات.",
      en: "Smart density: one page fits a long career without losing clarity — ideal for tech and consulting profiles.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 19,
    design: {
      ...baseDesign,
      accent: "#1d4ed8",
      spacing: "compact",
      sectionStyle: "caps",
      layout: "single",
      header: "stack",
      bullet: "dash",
    },
  },
  {
    id: "cloud-editorial",
    name: { ar: "كلاود تحريري", en: "Cloud Editorial" },
    description: {
      ar: "نبرة مجلاتية هادئة بخط مطبعي للعناوين ومساحات واسعة — يمنح الملف حضوراً راقياً بدون زخرفة.",
      en: "A quiet editorial voice with serif headings and wide margins — presence without ornament.",
    },
    category: "minimal",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 20,
    design: {
      ...baseDesign,
      accent: "#0f172a",
      headingFont: "serif",
      spacing: "airy",
      sectionStyle: "plain",
      layout: "single",
      header: "centered",
      bullet: "disc",
    },
  },
];

