import type { TemplateDef, TemplateDesign } from "./types";

export const baseDesign: TemplateDesign = {
  accent: "#1e3a5f",
  headingFont: "sans",
  spacing: "normal",
  sectionStyle: "line",
  layout: "single",
  header: "stack",
  bullet: "disc",
  supportsPhoto: false,
};

export const defaultTemplates: TemplateDef[] = [
  {
    id: "classic-ats",
    name: { ar: "كلاسيكي ATS", en: "Classic ATS" },
    description: {
      ar: "عمود واحد وعناوين واضحة بخطوط فاصلة، الأنسب لأنظمة تتبع المتقدمين.",
      en: "Single column with ruled headings — the safest structure for applicant tracking systems.",
    },
    category: "ats",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 1,
    design: {
      ...baseDesign,
      accent: "#1e3a5f",
      sectionStyle: "line",
      layout: "single",
      header: "stack",
      bullet: "disc",
    },
  },
  {
    id: "modern",
    name: { ar: "عصري", en: "Modern" },
    description: {
      ar: "ترويسة ملوّنة عريضة وعناوين بشرائط جانبية مع عمود واحد مقروء.",
      en: "Colour banner header with bar headings, kept in one readable column.",
    },
    category: "modern",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 2,
    design: {
      ...baseDesign,
      accent: "#0f766e",
      sectionStyle: "bar",
      layout: "single",
      header: "banner",
      bullet: "dash",
    },
  },
  {
    id: "executive",
    name: { ar: "تنفيذي", en: "Executive" },
    description: {
      ar: "ترويسة موزّعة وخط رصين بأحرف عنوان كبيرة، مناسب للمناصب القيادية.",
      en: "Split header with serif type and small-caps headings for leadership profiles.",
    },
    category: "executive",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 3,
    design: {
      ...baseDesign,
      accent: "#111827",
      headingFont: "serif",
      spacing: "airy",
      sectionStyle: "caps",
      layout: "single",
      header: "split",
      bullet: "square",
    },
  },
  {
    id: "minimal",
    name: { ar: "مبسّط", en: "Minimal" },
    description: {
      ar: "ترويسة موسّطة ومساحات بيضاء واسعة بدون أي زخرفة.",
      en: "Centred header, generous whitespace and no ornament at all.",
    },
    category: "minimal",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 4,
    design: {
      ...baseDesign,
      accent: "#334155",
      spacing: "airy",
      sectionStyle: "plain",
      layout: "single",
      header: "centered",
      bullet: "dash",
    },
  },
  {
    id: "saudi-professional",
    name: { ar: "سعودي مهني", en: "Saudi Professional" },
    description: {
      ar: "تنسيق عربي أولاً بترويسة خضراء وعمود جانبي للمهارات واللغات والروابط.",
      en: "Arabic-first layout with a green banner and a sidebar for skills, languages and links.",
    },
    category: "modern",
    atsFriendly: true,
    supportsRTL: true,
    active: true,
    order: 5,
    design: {
      ...baseDesign,
      accent: "#166534",
      sectionStyle: "bar",
      layout: "sidebar",
      header: "banner",
      bullet: "disc",
      supportsPhoto: true,
    },
  },
  {
    id: "creative",
    name: { ar: "إبداعي", en: "Creative" },
    description: {
      ar: "عمود جانبي ملوّن بالكامل مع دعم الصورة الشخصية — أقل ملاءمة لبعض أنظمة ATS.",
      en: "Full-colour side column with photo support — less suitable for some ATS parsers.",
    },
    category: "creative",
    atsFriendly: false,
    supportsRTL: true,
    active: true,
    order: 6,
    design: {
      ...baseDesign,
      accent: "#4c1d95",
      spacing: "compact",
      sectionStyle: "plain",
      layout: "sidebar-left",
      header: "stack",
      bullet: "square",
      supportsPhoto: true,
    },
  },
];
