/**
 * Achievement interview.
 *
 * Turns "I managed the sales team" into a documented achievement by asking for
 * the missing pieces one at a time: scope, period, action, result, and the
 * number behind the result. The number is optional on purpose — if the user
 * cannot back it, the fact is saved as "needs review" instead of being polished
 * into a claim nobody can defend. Nothing here is generated by AI: the stored
 * text is assembled from the user's own answers.
 */
import { useMemo, useState } from "react";
import { ArrowRight, Loader2, ShieldCheck, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useI18n } from "@/lib/i18n";
import { createEvidence, createFact } from "@/lib/career-facts";

type StepId = "task" | "scope" | "period" | "action" | "result" | "metric" | "proof";

type Step = {
  id: StepId;
  question: { ar: string; en: string };
  hint: { ar: string; en: string };
  multiline?: boolean;
  optional?: boolean;
};

const STEPS: Step[] = [
  {
    id: "task",
    question: {
      ar: "ما المهمة أو المسؤولية التي تريد تحويلها إلى إنجاز؟",
      en: "Which task or responsibility do you want to turn into an achievement?",
    },
    hint: {
      ar: "مثال: إدارة فريق المبيعات في المنطقة الوسطى.",
      en: "e.g. Managing the sales team in the central region.",
    },
  },
  {
    id: "scope",
    question: {
      ar: "ما حجم النطاق؟ (عدد الأشخاص، الميزانية، عدد العملاء)",
      en: "What was the scope? (people, budget, number of clients)",
    },
    hint: { ar: "اكتب ما تعرفه بدقة فقط.", en: "Only write what you know precisely." },
  },
  {
    id: "period",
    question: { ar: "في أي فترة زمنية؟", en: "Over what period?" },
    hint: { ar: "مثال: 2022 – 2024، أو خلال 6 أشهر.", en: "e.g. 2022–2024, or over 6 months." },
  },
  {
    id: "action",
    question: { ar: "ما الذي فعلته أنت تحديداً؟", en: "What exactly did you do?" },
    hint: {
      ar: "الإجراء الذي قمت به، لا ما فعله الفريق كله.",
      en: "Your action, not the whole team's.",
    },
    multiline: true,
  },
  {
    id: "result",
    question: { ar: "ما النتيجة التي تحققت؟", en: "What was the result?" },
    hint: {
      ar: "التغيير الذي حدث بسبب عملك.",
      en: "The change that happened because of your work.",
    },
    multiline: true,
  },
  {
    id: "metric",
    question: {
      ar: "هل هناك رقم يدعم النتيجة؟ (اتركه فارغاً إذا لم تكن متأكداً)",
      en: "Is there a number behind the result? (leave empty if unsure)",
    },
    hint: {
      ar: "لن نضيف رقماً لم تذكره. الأرقام غير المدعومة تبقى «تحتاج مراجعة».",
      en: "We never invent a number. Unbacked figures stay “needs review”.",
    },
    optional: true,
  },
  {
    id: "proof",
    question: {
      ar: "ما الدليل على ذلك؟ (تقرير، لوحة مؤشرات، شخص يمكنه التأكيد)",
      en: "What is the proof? (report, dashboard, someone who can confirm)",
    },
    hint: {
      ar: "اسم المصدر يكفي، لا ترفع مستندات سرية.",
      en: "A source name is enough — do not upload confidential documents.",
    },
    optional: true,
  },
];

export function AchievementInterview({
  userId,
  onSaved,
}: {
  userId: string;
  /** Called after the fact (and its evidence) are stored. */
  onSaved?: () => void;
}) {
  const { lang, dir } = useI18n();
  const ar = lang === "ar";
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState<string | null>(null);

  const step = STEPS[index];
  const value = step ? (answers[step.id] ?? "") : "";
  const done = index >= STEPS.length;

  // Assembled from the user's own words — no model in this path.
  const draft = useMemo(() => {
    const a = answers;
    const parts = [a["action"], a["result"]]
      .filter(Boolean)
      .join(ar ? " مما أدى إلى " : ", which led to ");
    const scope = a["scope"] ? (ar ? ` (${a["scope"]})` : ` (${a["scope"]})`) : "";
    const period = a["period"] ? (ar ? ` — ${a["period"]}` : ` — ${a["period"]}`) : "";
    return `${parts}${scope}${period}`.trim();
  }, [answers, ar]);

  const hasMetric = Boolean(answers["metric"]?.trim());
  const hasProof = Boolean(answers["proof"]?.trim());

  function next() {
    if (!step) return;
    if (!step.optional && !value.trim()) return;
    setIndex((i) => i + 1);
  }

  async function save() {
    if (!draft || busy) return;
    setBusy(true);
    setError(null);
    try {
      const fact = await createFact(userId, {
        type: "achievement",
        title: answers["task"]?.trim() || draft.slice(0, 80),
        value: draft,
        sourceType: "interview",
        sourceLabel: ar ? "مقابلة الإنجازات" : "Achievement interview",
        // A figure without proof is never stored as verified.
        verificationStatus: hasMetric && hasProof ? "verified" : "needs_review",
        metadata: {
          scope: answers["scope"] ?? "",
          period: answers["period"] ?? "",
          action: answers["action"] ?? "",
          result: answers["result"] ?? "",
          metric: answers["metric"] ?? "",
        },
      });
      if (!fact) throw new Error("save_failed");
      if (hasProof || hasMetric) {
        await createEvidence(userId, {
          factId: fact.id,
          evidenceType: hasMetric ? "metric" : "reference",
          title: answers["proof"]?.trim() || (ar ? "دليل الرقم" : "Metric source"),
          ...(answers["metric"]?.trim() ? { metricValue: answers["metric"].trim() } : {}),
          verified: false,
        });
      }
      setSaved(draft);
      setAnswers({});
      setIndex(0);
      onSaved?.();
    } catch {
      setError(ar ? "تعذّر الحفظ، حاول مرة أخرى." : "Saving failed, please try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div dir={dir} className="rounded-2xl border border-border bg-card p-4 text-start shadow-soft">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h3 className="flex items-center gap-2 text-sm font-bold">
          <Sparkles className="size-4 text-primary" />
          {ar ? "مقابلة الإنجازات" : "Achievement interview"}
        </h3>
        <Badge variant="secondary">
          {done
            ? ar
              ? "جاهز للحفظ"
              : "Ready to save"
            : ar
              ? `سؤال ${index + 1} من ${STEPS.length}`
              : `Question ${index + 1} of ${STEPS.length}`}
        </Badge>
      </div>

      {!done && step ? (
        <div className="mt-3 space-y-2">
          <p className="text-sm font-medium">{step.question[ar ? "ar" : "en"]}</p>
          <p className="text-xs text-muted-foreground">{step.hint[ar ? "ar" : "en"]}</p>
          {step.multiline ? (
            <Textarea
              rows={3}
              value={value}
              onChange={(e) => setAnswers((p) => ({ ...p, [step.id]: e.target.value }))}
            />
          ) : (
            <Input
              value={value}
              onChange={(e) => setAnswers((p) => ({ ...p, [step.id]: e.target.value }))}
            />
          )}
          <div className="flex items-center gap-2">
            <Button size="sm" onClick={next} disabled={!step.optional && !value.trim()}>
              {ar ? "التالي" : "Next"}
              <ArrowRight className="ms-2 size-4 rtl:rotate-180" />
            </Button>
            {index > 0 ? (
              <Button size="sm" variant="ghost" onClick={() => setIndex((i) => i - 1)}>
                {ar ? "رجوع" : "Back"}
              </Button>
            ) : null}
          </div>
        </div>
      ) : null}

      {done ? (
        <div className="mt-3 space-y-3">
          <div className="rounded-xl bg-muted/50 p-3 text-sm leading-[1.9]">{draft}</div>
          <p className="flex items-start gap-2 text-xs text-muted-foreground">
            <ShieldCheck className="mt-0.5 size-3.5 shrink-0" />
            {hasMetric && hasProof
              ? ar
                ? "سيُحفظ كحقيقة موثّقة مع دليلها."
                : "Will be stored as a documented fact with its evidence."
              : ar
                ? "سيُحفظ بحالة «تحتاج مراجعة» لعدم وجود رقم ودليل معاً."
                : "Will be stored as “needs review” because a number and its proof are not both present."}
          </p>
          <div className="flex flex-wrap items-center gap-2">
            <Button size="sm" onClick={save} disabled={busy || !draft}>
              {busy ? <Loader2 className="me-2 size-4 animate-spin" /> : null}
              {ar ? "حفظ في الخزانة" : "Save to vault"}
            </Button>
            <Button size="sm" variant="ghost" onClick={() => setIndex(0)}>
              {ar ? "تعديل الإجابات" : "Edit answers"}
            </Button>
          </div>
        </div>
      ) : null}

      {error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}
      {saved ? (
        <p className="mt-3 text-xs text-muted-foreground">
          {ar ? "تم الحفظ: " : "Saved: "}
          {saved}
        </p>
      ) : null}
    </div>
  );
}
