/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerEvidenceRouteImport } from './routes/career-evidence'
import { Route as CareerTwinRouteImport } from './routes/career-twin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ImportRouteImport } from './routes/import'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ResumesNewRouteImport } from './routes/resumes.new'
import { Route as ResumesIdEditRouteImport } from './routes/resumes.$id.edit'
import { Route as ResumesIdPreviewRouteImport } from './routes/resumes.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerEvidenceRoute = CareerEvidenceRouteImport.update({
  id: '/career-evidence',
  path: '/career-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTwinRoute = CareerTwinRouteImport.update({
  id: '/career-twin',
  path: '/career-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesNewRoute = ResumesNewRouteImport.update({
  id: '/resumes/new',
  path: '/resumes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIdEditRoute = ResumesIdEditRouteImport.update({
  id: '/resumes/$id/edit',
  path: '/resumes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIdPreviewRoute = ResumesIdPreviewRouteImport.update({
  id: '/resumes/$id/preview',
  path: '/resumes/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/career-evidence': typeof CareerEvidenceRoute
  '/career-twin': typeof CareerTwinRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/resumes/new': typeof ResumesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
  '/resumes/$id/preview': typeof ResumesIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/career-evidence': typeof CareerEvidenceRoute
  '/career-twin': typeof CareerTwinRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/resumes/new': typeof ResumesNewRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
  '/resumes/$id/preview': typeof ResumesIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/career-evidence': typeof CareerEvidenceRoute
  '/career-twin': typeof CareerTwinRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/resumes/new': typeof ResumesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/$id/edit': typeof ResumesIdEditRoute
  '/resumes/$id/preview': typeof ResumesIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ats'
    | '/auth'
    | '/career-evidence'
    | '/career-twin'
    | '/dashboard'
    | '/features'
    | '/import'
    | '/onboarding'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/jobs/$id'
    | '/resumes/new'
    | '/admin/'
    | '/jobs/'
    | '/resumes/$id/edit'
    | '/resumes/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ats'
    | '/auth'
    | '/career-evidence'
    | '/career-twin'
    | '/dashboard'
    | '/features'
    | '/import'
    | '/onboarding'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/jobs/$id'
    | '/resumes/new'
    | '/admin'
    | '/jobs'
    | '/resumes/$id/edit'
    | '/resumes/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ats'
    | '/auth'
    | '/career-evidence'
    | '/career-twin'
    | '/dashboard'
    | '/features'
    | '/import'
    | '/onboarding'
    | '/privacy'
    | '/templates'
    | '/terms'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/users'
    | '/jobs/$id'
    | '/resumes/new'
    | '/admin/'
    | '/jobs/'
    | '/resumes/$id/edit'
    | '/resumes/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtsRoute: typeof AtsRoute
  AuthRoute: typeof AuthRoute
  CareerEvidenceRoute: typeof CareerEvidenceRoute
  CareerTwinRoute: typeof CareerTwinRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ImportRoute: typeof ImportRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  JobsIdRoute: typeof JobsIdRoute
  ResumesNewRoute: typeof ResumesNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResumesIdEditRoute: typeof ResumesIdEditRoute
  ResumesIdPreviewRoute: typeof ResumesIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-evidence': {
      id: '/career-evidence'
      path: '/career-evidence'
      fullPath: '/career-evidence'
      preLoaderRoute: typeof CareerEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-twin': {
      id: '/career-twin'
      path: '/career-twin'
      fullPath: '/career-twin'
      preLoaderRoute: typeof CareerTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/new': {
      id: '/resumes/new'
      path: '/resumes/new'
      fullPath: '/resumes/new'
      preLoaderRoute: typeof ResumesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$id/edit': {
      id: '/resumes/$id/edit'
      path: '/resumes/$id/edit'
      fullPath: '/resumes/$id/edit'
      preLoaderRoute: typeof ResumesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$id/preview': {
      id: '/resumes/$id/preview'
      path: '/resumes/$id/preview'
      fullPath: '/resumes/$id/preview'
      preLoaderRoute: typeof ResumesIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AtsRoute: AtsRoute,
  AuthRoute: AuthRoute,
  CareerEvidenceRoute: CareerEvidenceRoute,
  CareerTwinRoute: CareerTwinRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ImportRoute: ImportRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  JobsIdRoute: JobsIdRoute,
  ResumesNewRoute: ResumesNewRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResumesIdEditRoute: ResumesIdEditRoute,
  ResumesIdPreviewRoute: ResumesIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
