// This file is automatically generated. Keep production env access compatible with Vite replacement.
import { createClient } from "@supabase/supabase-js";
import type { PublicRuntimeConfig } from "@/lib/public-runtime-config.functions";
import type { Database } from "./types";

let runtimeConfig: PublicRuntimeConfig | undefined;

export function setSupabaseRuntimeConfig(config: PublicRuntimeConfig | undefined) {
  if (!config?.configured) return;
  runtimeConfig = config;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Prefer Vite replacement when available. Lovable production can also bootstrap
  // the same browser-safe values from its server runtime through the root loader.
  // @ts-expect-error -- direct Vite env access is intentionally required for build-time replacement.
  const viteUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
  const vitePublishableKey =
    // @ts-expect-error -- direct Vite env access is intentionally required for build-time replacement.
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

  const SUPABASE_URL = viteUrl || runtimeConfig?.supabaseUrl || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    vitePublishableKey ||
    runtimeConfig?.supabasePublishableKey ||
    process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
